#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


# In[2]:


df = pd.read_csv('D:/UOM_3rd_Year/Semester 6/Data mining/Kaggle Competition/house-prices-advanced-regression-techniques/train.csv')


# In[3]:


df


# In[4]:


df.shape


# In[5]:


df.head()


# In[6]:


sns.heatmap(df.isnull(),yticklabels=False,cbar=False)


# In[7]:


df.info()


# In[8]:


df.drop(['Alley'],axis=1,inplace=True)


# In[9]:


df.drop(['GarageYrBlt'],axis=1,inplace=True)


# In[10]:


df.drop(['PoolQC','Fence','MiscFeature'],axis=1,inplace=True)


# In[11]:


df.drop(['Id'],axis=1,inplace=True)


# In[12]:


df['LotFrontage']=df['LotFrontage'].fillna(df['LotFrontage'].mean())


# In[13]:


df['BsmtCond']=df['BsmtCond'].fillna(df['BsmtCond'].mode()[0])
df['BsmtQual']=df['BsmtQual'].fillna(df['BsmtQual'].mode()[0])


# In[14]:


df['FireplaceQu']=df['FireplaceQu'].fillna(df['FireplaceQu'].mode()[0])
df['GarageType']=df['GarageType'].fillna(df['GarageType'].mode()[0])


# In[15]:


df['GarageFinish']=df['GarageFinish'].fillna(df['GarageFinish'].mode()[0])
df['GarageQual']=df['GarageQual'].fillna(df['GarageQual'].mode()[0])
df['GarageCond']=df['GarageCond'].fillna(df['GarageCond'].mode()[0])


# In[16]:


df['MasVnrType']=df['MasVnrType'].fillna(df['MasVnrType'].mode()[0])
df['MasVnrArea']=df['MasVnrArea'].fillna(df['MasVnrArea'].mode()[0])


# In[17]:


df['BsmtExposure']=df['BsmtExposure'].fillna(df['BsmtExposure'].mode()[0])


# In[18]:


df['BsmtFinType2']=df['BsmtFinType2'].fillna(df['BsmtFinType2'].mode()[0])


# In[19]:


df.shape


# In[20]:


df.dropna(inplace=True)


# In[21]:


df.shape


# In[22]:


columns=['MSZoning','Street','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood',
         'Condition2','BldgType','Condition1','HouseStyle','SaleType',
        'SaleCondition','ExterCond',
         'ExterQual','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2',
        'RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Heating','HeatingQC',
         'CentralAir',
         'Electrical','KitchenQual','Functional',
         'FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive']


# In[23]:


def category_onehot_multcols(multcolumns):
    df_final=final_df
    i=0
    for fields in multcolumns:
        
        print(fields)
        df1=pd.get_dummies(final_df[fields],drop_first=True)
        
        final_df.drop([fields],axis=1,inplace=True)
        if i==0:
            df_final=df1.copy()
        else:
            
            df_final=pd.concat([df_final,df1],axis=1)
        i=i+1
       
        
    df_final=pd.concat([final_df,df_final],axis=1)
        
    return df_final


# In[24]:


main_df=df.copy()


# In[25]:


test_df=pd.read_csv('formulatedtest.csv')


# In[26]:


test_df.shape


# In[27]:


test_df.head()


# In[28]:


final_df=pd.concat([df,test_df],axis=0)


# In[29]:


final_df['SalePrice']


# In[30]:


final_df.shape


# In[31]:


final_df=category_onehot_multcols(columns)


# In[32]:


final_df.shape


# In[33]:


final_df =final_df.loc[:,~final_df.columns.duplicated()]


# In[34]:


final_df.shape


# In[35]:


final_df


# In[36]:


df_Train=final_df.iloc[:1422,:]
df_Test=final_df.iloc[1422:,:]


# In[37]:


df_Train.head()


# In[38]:


df_Test.head()


# In[39]:


df_Train.shape


# In[40]:


df_Test.drop(['SalePrice'],axis=1,inplace=True)


# In[41]:


X_train=df_Train.drop(['SalePrice'],axis=1)
y_train=df_Train['SalePrice']


# In[42]:


pip install xgboost


# In[43]:


import xgboost
classifier=xgboost.XGBRegressor()
classifier.fit(X_train,y_train)


# In[50]:


import pickle
filename = 'finalized_model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(classifier, file)


# In[51]:


y_pred=classifier.predict(df_Test)


# In[52]:


y_pred


C In[56]:


##Create Sample Submission file and Submit using ANN
pred=pd.DataFrame(y_pred)
sub_df=pd.read_csv('D:/UOM_3rd_Year/Semester 6/Data mining/Kaggle Competition/house-prices-advanced-regression-techniques/sample_submission.csv')
datasets=pd.concat([sub_df['Id'],pred],axis=1)
datasets.columns=['Id','SalePrice']
datasets.to_csv('D:/UOM_3rd_Year/Semester 6/Data mining/Kaggle Competition/house-prices-advanced-regression-techniques/sample_submission.csv',index=False)

###Prediciton and selecting the Algorithm

import xgboost
classifier=xgboost.XGBRegressor()
import xgboost
regressor=xgboost.XGBRegressor()
booster=['gbtree','gblinear']
base_score=[0.25,0.5,0.75,1]
## Hyper Parameter Optimization


n_estimators = [100, 500, 900, 1100, 1500]
max_depth = [2, 3, 5, 10, 15]
booster=['gbtree','gblinear']
learning_rate=[0.05,0.1,0.15,0.20]
min_child_weight=[1,2,3,4]

# Define the grid of hyperparameters to search
hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'learning_rate':learning_rate,
    'min_child_weight':min_child_weight
    'booster':booster,
    'base_score':base_score
    }
# Set up the random search with 4-fold cross validation
random_cv = RandomizedSearchCV(estimator=regressor,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',n_jobs = 4,
            verbose = 5, 
            return_train_score = True,
            random_state=42)

random_cv.fit(X_train,y_train)





